### ISSUE TITLE
Chaining promises using PromiseMock

### ISSUE THREAD

**Issue by ShaySEY** [slavik57/promise-sync#7]
Hi,
First, thank you for this amazing library!

I have an issue that when I use the PromiseMock for a single method in promise chain calls, the mock does not call to the other mock.

Can you please fix this?

Thanks,
Shay

**Comment by slavik57** [comment]
Was kinda hard to understand what you meant but after talking to you personally I understood.

For others:
The issue is when chaining multiple then statements and returning a real promise from one of the success callbacks, the real promise was treated like a return value and not a promise so the next then statement got the promise instead of its result.
